/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentation;

import CrudManager.AccountManager;
import CrudManager.CustomerJDBCManager;
import CrudManager.CustomerManager;
import Domain.Account;
import Domain.Customer;
import javax.swing.JFrame;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import org.apache.log4j.Logger;
import Domain.Worker;

/**
 *
 * @author Dinham
 */
public class AddAccountExist extends javax.swing.JFrame {
    
    JFrame f = new JFrame();
    CustomerManager customerMgr = new CustomerManager();
    Customer customer = new Customer();
    Account ac = new Account();
    Worker worker =new Worker();
    

     private static final Logger log = Logger.getLogger(AddAccountExist.class);
    /**
     * Creates new form AddAccount
     */
    public AddAccountExist() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jIAddAccountExisting = new javax.swing.JInternalFrame();
        balanceTextField = new javax.swing.JTextField();
        loanTextField = new javax.swing.JTextField();
        installTextField = new javax.swing.JTextField();
        dateOpenTextField = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        emailTextField = new javax.swing.JTextField();
        telTextField = new javax.swing.JTextField();
        fNameText = new javax.swing.JTextField();
        lNameText = new javax.swing.JTextField();
        dobTextField = new javax.swing.JTextField();
        trnTextField2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jButton3 = new javax.swing.JButton();
        trnTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jIAddAccountExisting.setVisible(true);

        balanceTextField.setToolTipText("Balance");

        loanTextField.setToolTipText("Loan Amount");

        installTextField.setToolTipText("Installments");

        dateOpenTextField.setToolTipText("Date Opened");

        jTextField11.setToolTipText("Date Closed");
        jTextField11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField11ActionPerformed(evt);
            }
        });

        jButton1.setText("Cancel");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Save");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel3.setText("Account Info");

        emailTextField.setEditable(false);
        emailTextField.setToolTipText("Email");

        telTextField.setEditable(false);
        telTextField.setToolTipText("Telephone");

        fNameText.setEditable(false);
        fNameText.setToolTipText("First Name");

        lNameText.setEditable(false);
        lNameText.setToolTipText("Last Name");

        dobTextField.setEditable(false);
        dobTextField.setToolTipText("DOB");

        trnTextField2.setEditable(false);
        trnTextField2.setToolTipText("TRN");

        jLabel2.setText("Customer Info");

        jButton3.setText("Search");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        trnTextField.setToolTipText("Enter TRN");

        jLabel1.setText("Add Account For Existing Customer");

        javax.swing.GroupLayout jIAddAccountExistingLayout = new javax.swing.GroupLayout(jIAddAccountExisting.getContentPane());
        jIAddAccountExisting.getContentPane().setLayout(jIAddAccountExistingLayout);
        jIAddAccountExistingLayout.setHorizontalGroup(
            jIAddAccountExistingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jIAddAccountExistingLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jIAddAccountExistingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jIAddAccountExistingLayout.createSequentialGroup()
                        .addComponent(emailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(telTextField))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jIAddAccountExistingLayout.createSequentialGroup()
                        .addGroup(jIAddAccountExistingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jIAddAccountExistingLayout.createSequentialGroup()
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(50, 50, 50)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jIAddAccountExistingLayout.createSequentialGroup()
                                .addComponent(fNameText, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lNameText, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(dobTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(trnTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel1)
                            .addGroup(jIAddAccountExistingLayout.createSequentialGroup()
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(trnTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jIAddAccountExistingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jIAddAccountExistingLayout.createSequentialGroup()
                                    .addComponent(dateOpenTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jIAddAccountExistingLayout.createSequentialGroup()
                                    .addComponent(balanceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(loanTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(installTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 13, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jIAddAccountExistingLayout.setVerticalGroup(
            jIAddAccountExistingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jIAddAccountExistingLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addGroup(jIAddAccountExistingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(trnTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(jIAddAccountExistingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dobTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(trnTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jIAddAccountExistingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(telTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(jIAddAccountExistingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(balanceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(loanTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(installTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jIAddAccountExistingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dateOpenTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(jIAddAccountExistingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        jDesktopPane1.setLayer(jIAddAccountExisting, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jIAddAccountExisting)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jIAddAccountExisting, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jDesktopPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jDesktopPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField11ActionPerformed

    //Cancel and return to dashboard
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        AddAccountPrompt addAccountPrompt = new AddAccountPrompt();
        this.setVisible(false);
        addAccountPrompt.setVisible(true);
        
        //db.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    //Save button
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try{
            
            AccountManager accountManager = new AccountManager();
            
            if(balanceTextField.getText().isBlank() && balanceTextField.getText().isEmpty() 
                    || loanTextField.getText().isBlank() && loanTextField.getText().isEmpty()
                    || installTextField.getText().isBlank() && installTextField.getText().isEmpty()
                    || dateOpenTextField.getText().isBlank() && dateOpenTextField.getText().isEmpty())
            {
                //JFrame f = new JFrame();
                JOptionPane.showMessageDialog(f, "Missing information, please review.");
            }else
            {
                
                JOptionPane.showMessageDialog(f, "Customer info Saved");
                this.setVisible(false);
                
                
                ac.setBalance(Float.parseFloat(balanceTextField.getText()));
                ac.setLoanAmount(Float.parseFloat(loanTextField.getText()));
                ac.setMonthlyInstalment(Float.parseFloat(installTextField.getText()));
                ac.setDateOpened(dateOpenTextField.getText());
                ac.setCustomerTRN(Integer.parseInt(trnTextField2.getText()));
                ac.setWorkerId(worker.getId());
                
                System.out.print(evt);
                
                
                 Account account1 = new Account(ac,customer,worker);
                 
                 //account1.setAccountnumber(ac.getAccountnumber());
                 //account1.setAccountnumber(String.valueOf(1000));
                 account1.setBalance(ac.getBalance());
                 account1.setLoanAmount(ac.getLoanAmount());
                 account1.setMonthlyInstalment(ac.getMonthlyInstalment());
                 account1.setDateOpened(ac.getDateOpened());
                 account1.setDateClosed(ac.getDateClosed());
                 account1.setCustomerTRN(Integer.parseInt(customer.getTrn()));
                 account1.setWorkerId(worker.getId());
                
                 
                JOptionPane.showMessageDialog(f, "Customer info Saved"+ ac.getBalance()+ ac.getLoanAmount() + ac.getCustomerTRN());
                 
                //accountManager.addAccount(ac);
                //accountManager.addAccountJDBC(account1);
                accountManager.addAccountJDBC(ac);
            }
            
        }catch(Exception ex) 
        {
            int input = JOptionPane.showConfirmDialog(null,"Error customer info.", "", JOptionPane.DEFAULT_OPTION);
            	System.out.println(ex);
                log.info(ex.getMessage());
        }
        

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try{
            
        
            if(trnTextField.getText().isEmpty() && trnTextField.getText().isBlank())
            {
                //JFrame f = new JFrame();
                JOptionPane.showMessageDialog(f, "Invalid Data");
            }
            else
            {
                //CustomerJDBCManager customerMgr = new CustomerJDBCManager();
                //working instance of Customer Manager
                

                //Passes data from crudmanager to customer class
                //working method
                customer = customerMgr.getCustomer(trnTextField.getText().trim());
                //customer = customerMgr.getCustomerJDBC(trnTextField.getText().trim());

                //Push values to the uneditable text boxes.
                fNameText.setText(customer.getFirstname());
                lNameText.setText(customer.getLastname());
                dobTextField.setText(customer.getDob());
                trnTextField2.setText(customer.getTrn());
                emailTextField.setText(customer.getEmail());
                telTextField.setText(customer.getTelephoneNum());
                
                System.out.println(customer.getFirstname());
            }
        }catch (Exception ex) {
            
            int input = JOptionPane.showConfirmDialog(null, 
		                  "Error customer info.", "", JOptionPane.DEFAULT_OPTION);
            	System.out.println(ex); 
                log.info(ex.getMessage());
            
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddAccountExist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddAccountExist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddAccountExist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddAccountExist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddAccountExist().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField balanceTextField;
    private javax.swing.JTextField dateOpenTextField;
    private javax.swing.JTextField dobTextField;
    private javax.swing.JTextField emailTextField;
    private javax.swing.JTextField fNameText;
    private javax.swing.JTextField installTextField;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JInternalFrame jIAddAccountExisting;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField lNameText;
    private javax.swing.JTextField loanTextField;
    private javax.swing.JTextField telTextField;
    private javax.swing.JTextField trnTextField;
    private javax.swing.JTextField trnTextField2;
    // End of variables declaration//GEN-END:variables
}
